- odata-client-generator/pom.xml
- odata-client-msgraph-beta/pom.xml
- odata-client-msgraph-beta/src/main/java/com/github/davidmoten/msgraph/beta/MsGraph.java
- odata-client-msgraph-client-builder/pom.xml
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/AccessTokenProvider.java
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/AuthenticationEndpoint.java
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/Authenticator.java
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/BearerAuthenticator.java
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/ClientCredentialsAccessTokenProvider.java
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/Creator.java
- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/MsGraphClientBuilder.java
- odata-client-msgraph/pom.xml
- odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/MsGraph.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/AdHocMain.java
- odata-client-runtime/pom.xml
- pom.xml
Update packaging to generate OSGI manifest data, to better support deployment in OSGI environments.
Sorry - take #2 on this pull request, there was a missing commit.
The first commit is simple enough, it just uses the maven-bundle-plugin to add the OSGI headers to the manifest of each jar file.
The second commit is more of a breaking change.  OSGI does not like multiple bundles (jar files) providing classes from the same package namespace.  In this case, you're using the same namespace for the odata-client-msgraph and odata-client-msgraph-client-builder packages (com.github.davidmoten.msgraph).   I've moved the builder classes into their own namespace, but this might have implications for client code if people have used any of the builder classes directly.
> Osgi bundles

- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/resources/response-attachments-one-item.json
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionEntityRequestOptionsBuilder.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java
as discussed in #8 this should work. I'll confirm when I write a unit test for it. I already have a unit test somewhere that returns a collection of Attachment and the objects returned in the list are of type ItemAttachment,  FileAttachment so I should be able to reuse that data.
> add support for filtering on derived types to entity collection requests

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Names.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Util.java
- odata-client-generator/src/main/odata/msgraph-metadata.xml
- odata-client-generator/src/test/java/com/github/davidmoten/odata/client/generator/GeneratorTest.java
- odata-client-generator/src/test/java/com/github/davidmoten/odata/client/generator/UtilTest.java
- odata-client-msgraph-beta/src/main/odata/msgraph-beta-metadata.xml
- odata-client-msgraph/pom.xml
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java
Aliases are replaced with full namespaces as an early step in metadata processing and this needed to be tightened up generally for when one alias contains another alias in a String sense. This wasn't necessary to support the new v1.0 metadata for msgraph but was noticed along the way. 
The unit test that processes metadata in odata-client-generator project needed to be supplied with extra SchemaOptions to handle the extra schema now present in v1.0 metadata.
> Support extra schema in msgraph v1.0 metadata, improve schema alias support

- odata-client-runtime/pom.xml
See discussion in #6 and https://github.com/davidmoten/guava-mini/pull/1.
@badfish69 can you review please.
> OSGi support: upgrade guava-mini and remove unused jcip-annotations dep

- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java
- odata-client-msgraph/src/test/resources/response-get-collection-error.json
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPage.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageNonEntityRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
- odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/CollectionPageTest.java
As mentioned in #15, testing showed that when a collection get like `client.users().get()` fails with a 403 for example, a NullPointerException is thrown because the value array is not present in the response JSON. In fact the error status code should be detected and an informative error thrown.
> Error response from collection get should be informative

- odata-client-msgraph-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/MsGraphClientBuilder.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/AdHocMain.java
If the SSL handshake with MsGraph hung then the configured timeout did not apply (see bug report in Apache httpclient https://issues.apache.org/jira/browse/HTTPCLIENT-2090).
The workaround is to use a PoolingHttpConnectionManager with the read timeout specified in the SocketConfig.
@superevensteven
> ensure socket timeout honoured during SSL handshake

- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/resources/response-list-items-expand-fields.json
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/InjectableValuesFromFactories.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
As mentioned in #35, serialization of a list of items ends with all items sharing the same instance of `UnmappedValues` and `ChangedFields`. To fix this we could prevent injection of those fields but I'd like to preserve that injection using a factory instead rather than remove injection altogether out of uncertainty that we have test coverage of the original motivation to use injection.
I've copied `InjectableValues.Std` from Jackson lib and made `InjectableValuesFromFactories` and used that in `Serializer.deserialize` and `Serializer.deserializeWithParametricType`.
The test from #35 passes with this change.
Upon reflection I think the injection of UnmappedValues and ChangedFields is explicitly performed because of nervousness about NPEs from uninitialized fields being used (though it …
> Use injectable factories so that UnmappedValues and ChangedFields are initialized properly in deserialized lists

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphExplorerMain.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java
- odata-client-msgraph/src/test/resources/response-expand-attachments.json
- odata-client-msgraph/src/test/resources/response-messages.json
- odata-client-msgraph/src/test/resources/response-user-expand-with-drive.json
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/EntityRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ODataValue.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/UnmappedFields.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/UnmappedFields.java
- src/docs/FileAttachment.java
The example below explains how when expand is used the associated collection request is satisfied by looking at the unmapped fields rather than performing another network call. Similarly for an entity request.
```java
Message m = client
.users("fred")
.messages("123")
.expand("attachments")
.get();
// because expand used this next call will not make a network request 
// but rather get its result from the unmapped fields of m
List<Attachment> list = m.getAttachments().toList();
```
Raised in #47
> Support expand for entity requests and entity collection requests

- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CustomRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/HasContext.java
and rename methods `postJson` to `postString` and `postJsonReturnsJson` to `postStringReturnsString` (breaking change).
> support relative urls in CustomRequest

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/EntityType.java
When one entity without keys (invalid) is found the build fails fast. This PR ensures that all entities without keys are logged to the console before failing.
> odata-client-generator - log all entities that have no keys before failing

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/Action.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/Function.java
- odata-client-generator/src/main/odata/msgraph-metadata.xml
- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/GraphExplorerHttpService.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphExplorerMain.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java
- odata-client-msgraph/update-metadata.sh
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ActionRequestReturningStream.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ContextPath.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/FunctionRequestReturningNonCollection.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/FunctionRequestReturningNonCollectionUnwrapped.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/FunctionRequestReturningStream.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/HttpService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/InlineParameterSyntax.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Path.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/StreamProvider.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/StreamProviderBase.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ApacheHttpClientHttpService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/DefaultHttpService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/Util.java
- odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/CollectionPageTest.java
- odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/InlineParameterSyntaxTest.java
- odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test6ServiceTest.java
See discussion in #93 
* Parameters for actions and functions are appended directly to final segment rather than being a separate segment (Bug fix) 
* Override msgraph metadata so that functions and actions that return `graph.report` return `Edm.Stream` instead.
* Add support for returning Edm.Stream from function/action
* Update msgraph v1.0 metadata (Dec 29 2020)
> Fix msgraph metadata for report functions and actions, support returning Edm.Stream from function/action 

- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/resources/request-user-patch.json
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/HttpResponse.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java
As discussed in #99, add the ability to specify the returned status code from any unit test calls using TestingService.
> TestingService - support setting response status code for all methods

- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/client/builder/MicrosoftClientBuilder.java
- odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/MsGraph.java
As discussed in #103. Here's an example of use taken from the MsGraph class:
```java
public static MicrosoftClientBuilder.Builder3<GraphService> tenantName(String tenantName) {
return MicrosoftClientBuilder //
.baseUrl(MSGRAPH_1_0_BASE_URL) //
.creator(GraphService::new) //
.addSchema(odata.msgraph.client.schema.SchemaInfo.INSTANCE) //
.addSchema(odata.msgraph.client.callrecords.schema.SchemaInfo.INSTANCE) //
.pathStyle(PathStyle.IDENTIFIERS_AS_SEGMENTS) //
.build() //
.tenantName(tenantName) //
.resource(GraphConstants.RESOURCE_MS_GRAPH) //
.scope(GraphConstants.SCOPE_MS_GRAPH_DEFAULT);
}
```
> enable setting of path style in MicrosoftClientBuilder 

- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ApacheHttpClientHttpService.java
As discussed in #123, this PR fixes an NPE in `ApacheHttpClientService` and also ensures that another NPE does not occur if debug logging is enabled.
> Fix NPE when service call returns no content (HTTP 204)

- README.md
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/Structure.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/EntityRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/EntityRequestOptionsBuilder.java
- odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test8ServiceTest.java
As mentioned in #128, if a Media Entity or an Entity with a stream property is returned without full metadata then the stream may not be available (`Optional.empty()`). This PR defaults to setting `.metadataFull()` for Media Entities or entities with stream properties when the object is returned via an entity request. For example the call below will work without having to call `.metadataFull()` before the first `.get()`.
```java
byte[] bytes = client 
.drives(driveId) 
.items(itemId)
.get()
.getContent()
.get()
.getBytes();
```
Note that explicitly setting the metadata value (say by calling `.metadataMinimal()`) will override the default setting.
This PR is unit tested.
cc @AmudhaNila
> Default to full metadata when returning an entity that has a stream

- odata-client-generator/pom.xml
The `<schemaDirectory>` element is no longer used with the jaxb2-maven-plugin (it was a 1.x option, as I discovered in the answer for here: https://stackoverflow.com/questions/54933138/how-do-i-define-schema-directory-in-jaxb2-maven-plugin-version-2-4) Updated the pom to use the correct parameter.
> Update XJC parameters to jaxb2-maven-plugin compatibility

- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/authentication/ClientCredentialsAccessTokenProvider.java
- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/client/builder/MicrosoftClientBuilder.java
As raised in #147, this is the fix.
> Fix proxy values not being used to get access token in MicrosoftClientBuilder

- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/RequestOptions.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/StreamProvider.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestOptionsImpl.java
As discussed in #152 the ability to specify request headers for a stream download is needed. While I was there I added custom timeouts.
> Specify request headers and timeouts to StreamProvider

- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/edm/UnsignedByte.java
- odata-client-test-service/src/test/java/com/github/davidmoten/odata/test/DemoServiceTest.java
As per discussion in #164, `UnsignedByte` needs a `@JsonValue` annotation on the `value` field to serialize properly.
> Fix serialization of UnsignedByte

- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/GraphExplorerHttpService.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/resources/response-drive-item-put.json
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CustomRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/HttpService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/RequestHeader.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ApacheHttpClientHttpService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/DefaultHttpService.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
- odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/CollectionPageTest.java
As it becomes obvious that the HTTP verb itself doesn't limit whether a request has content or returns response body I've rejigged the HttpService interface (and updated all implementations of HttpService).
Inspiration for the work was adding a custom request put example for #173.
> Simplify HttpService and fix some wrong signatures in CustomRequest

- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ApacheHttpClientHttpService.java
As discussed in #177 a post was getting sent as a put. The problem had been present for a while but that code path wasn't used as much till a recent HttpService refactor #176.
Simple fix obviously.
> Fix post in ApacheHttpClientHttpService.toRequestBase

- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/authentication/BearerAuthenticator.java
- odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/msgraph/builder/GraphExplorerHttpService.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphExplorerMain.java
Just noticed that this code was failing with a 403, turned out that Microsoft had moved the Graph Explorer sandbox to another host graph.office.net.
> migrate GraphExplorer code to use new hostname graph.office.net

- README.md
- odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/email/EmailTest.java
* Some builder methods were at default access and should have been public. 
* `bodyType` is required and is now included
* moved `EmailTest` to another package to test visibility
Apologies for including tab to spaces conversion as well.
> fix Email builder (builder methods not public, bodyType missed)

- odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/email/EmailTest.java
The builder already allows the specification of attachments using method and builder chaining but is not at all convenient if you have an arbitrary list of attachments you need to specify.
This PR adds `.attachments(List<Attachment>)` to the builder  (and `Attachment.*` builder methods as well.
See the new test in this PR for an example.
> Support attachment list in Email send builder

- odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java
intermediate chained builder names were a bit too abstract Builder1, Builder2 etc and breaking changes might have been introduced by inserting new ones and then reordering. More descriptive names are now used.
> rename send email builder class names

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/SchemaOptions.java
- odata-client-maven-plugin/src/main/java/org/davidmoten/odata/client/maven/GeneratorMojo.java
- odata-client-msgraph-beta/pom.xml
- odata-client-msgraph/pom.xml
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java
- odata-client-test-unit/pom.xml
- odata-client-test-unit/src/main/odata/metadata3.xml
- odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test3ServiceTest.java
As raised in #298, when a special request header (`Prefer: include-unknown-enum-members`) is set a returned value that is an EnumType may fail to deserialize (will throw). Microsoft Graph uses a sentinel value `unknownFutureValue` in enums that is an obvious target to use for unknown values. When this enum value is present we can annotate the member with `@JsonEnumDefaultValue` and deserialization will associate unknown values with that member (admittedly with the loss of the actual enumerated value).
This is an important enhancement because Microsoft add new members to existing Graph enumeration types all the time (I see them when I review metadata changes every month). Many enumerations appear to have the `unknownFutureValue` sentinel (231 of 429 EnumTypes across the Graph API have the …
> Support json enum default value for deserializing unknown values (evolvable enums)

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Names.java
- odata-client-test-unit/src/main/odata/metadata1.xml
... in method `Names.getGetterMethodWithoutGet`. 
Raised in #347
This PR includes a unit test that failed with a compile error to demonstrate the problem.
> ensure reserved words are checked using lower case

- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java
Jackson 2.15 introduced a stream size limit so that Jackson would not deserialize >5MB streams (!!!).
This PR modifies the ObjectMappers held in Serializer.java to allow unlimited streams as before. A later change will allow customizations of the Serializer ObjectMapper so that users can make adjustments themselves.
> remove stream limit of 5MB so don't fail downloading big emails/files

- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageNonEntityRequest.java
- odata-client-test-unit/src/main/odata/metadata6.xml
- odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test6ServiceTest.java
- odata-client-test-unit/src/test/resources/response-function-returns-empty-collection.json
See #439
I checked the OData v4.01 [spec](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_Functions) on this and a Function should use *inline parameter syntax*. This PR ensure that.
A unit test is added to test this scenario.
> Ensure Function parameters are url query parameters when a collection is returned

- odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java
- odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ActionRequestReturningNonCollectionUnwrapped.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionEntityRequestOptionsBuilder.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CustomRequest.java
- odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
- odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test1ServiceTest.java
This PR is a breaking change to fix #450 in that calls like below instead of returning a `Message` will return an `Optional<Message>`. This is because certain headers will bring this us about with MsGraph and because Dynamics CRM returns HTTP No-Content by default for a lot of stuff (one actually has to set a header to ensure full response if desired). 
```java
client.me().messages().post(m)
```
This is of course a **breaking change** but necessary.
> return optional from post and patch calls in case no content in response #450

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Names.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/ComplexType.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/EntityType.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/Structure.java
- odata-client-generator/src/main/odata/msgraph-metadata.xml
- odata-client-generator/src/test/java/com/github/davidmoten/odata/client/generator/GeneratorTest.java
- odata-client-msgraph/pom.xml
identically named base types from different schemas were being picked up into the builders of types from other schemas. This PR fixes that issue.
> update msgraph metadata v1 and fix heirarchy related compile errors

- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Names.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/Property.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/PropertyRef.java
- odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/Structure.java
- odata-client-test-unit/src/main/odata/metadata1.xml
As discussed in #531 a property `package` and a navigation property `Package` have distinct names but generate to compile errors because of naming conflict. This PR fixes that issue so that conflicting properties have 1 or more underscores suffixed to their field/getter names.
> Field name conflicts when property names differ by case only
