odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/SerializerTest.java
Some minor fixes.
The first is to add a missing expand() method definition in CollectionPageEntityRequest, the second is to fix support for provisioning (via patch) of null values to target endpoints.
=> Misc fixes

odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/SerializerTest.java, odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test1ServiceTest.java, src/docs/FileAttachment.java
=> fix modifying a field to null should be reflected in serialized changes

README.md, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ActionRequestNoReturn.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ActionRequestReturningNonCollection.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionEntityRequestOptionsBuilder.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionNonEntityRequestOptionsBuilder.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageNonEntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionRequestOptions.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CustomRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/EntityRequestOptions.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/FunctionRequestReturningNonCollection.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/NonEntityRequestOptions.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/RequestHeader.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/RequestOptions.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java, odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test1ServiceTest.java
As per discussion in #15, allowing url override for getting collections. 
Example:
```java
String nextLink = "https://blahblah";
List<User> users = client 
.users()
.urlOverride(nextLink)
.get().currentPage();
```
=> Allow url override and add maxPageSize method for getting collections

odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-msgraph/src/test/resources/response-contacts-minimal-json.json, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPage.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/MinimalPage.java
=> add CollectionPage.toJsonMinimal() method

odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ClientException.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ApacheHttpClientHttpService.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
=> add getStatusCode() method to ClientException

odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionNonEntityRequestOptionsBuilder.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageNonEntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/EdmSchemaInfo.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/Util.java
=> implement filter(Class) for non-entity collections (complex types)

odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Retries.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/RetryException.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/StreamUploader.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/StreamUploaderChunked.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/StreamUploaderSingleCall.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/UploadStrategy.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/UploadStrategyChunked.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/UploadStrategySingleCall.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/RetriesTest.java
For example:
```java
Thumbnail thumbnail = ...;
thumbnail 
.putChunkedContent() 
.get()
.readTimeout(10, TimeUnit.MINUTES)
.upload(inputStream, inputStreamSize, chunkSize, 
Retries.builder().maxRetries(10).cappedExponentialRetry(1, 2.0, 30, TimeUnit.SECONDS)); 
```
=> allow retries to be specified to StreamUploaderChunked

odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphExplorerMain.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-msgraph/src/test/resources/response-users-delta-latest-next-2.json, odata-client-msgraph/src/test/resources/response-users-delta-latest-next-3.json, odata-client-msgraph/src/test/resources/response-users-delta-latest-next.json, odata-client-msgraph/src/test/resources/response-users-delta-latest.json, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionEntityRequestOptionsBuilder.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionNonEntityRequestOptionsBuilder.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPage.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageEntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPageNonEntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionRequestOptions.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/PageListener.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Paged.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Serializer.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Util.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/CollectionPageTest.java
As discussed in #37.
An example of delta support is 
```java
// Get an empty delta that you can use as a starting point for later deltas
CollectionPage<User> delta = client.users().delta().deltaTokenLatest().get();
// a while later
delta = delta.nextDelta();
delta.forEach(System.out::println);
```
I'll add docs to README.md after merge.
=> add delta support

README.md, odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/EmailTest.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/Util.java
=> add email send helper

odata-client-microsoft-dynamics/src/test/java/com/github/davidmoten/ms/dynamics/DynamicsMain.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphExplorerMain.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-msgraph/src/test/resources/response-users-delta-empty.json, odata-client-msgraph/src/test/resources/response-users-one-page.json, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPage.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ObjectOrDeltaLink.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/WithDeltaLinkTest.java
As a serialization helper discussed in #44 I've added `CollectionPage.streamWithDeltaLink()` method which returns a stream of ObjectOrDeltaLink objects.
=> Add CollectionPage.streamWithDeltaLink method

odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java, odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Names.java, odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/SchemaOptions.java, odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/model/EntitySet.java, odata-client-maven-plugin/src/main/java/org/davidmoten/odata/client/maven/GeneratorMojo.java, odata-client-maven-plugin/src/main/java/org/davidmoten/odata/client/maven/Schema.java, odata-client-microsoft-dynamics/pom.xml, odata-client-microsoft-dynamics/src/main/odata/microsoft-dynamics-crm4-v9.1-metadata.xml
=> Optionally ignore missing entity set

odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/authentication/BearerAuthenticator.java, odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/authentication/ClientCredentialsAccessTokenProvider.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ClientException.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/ClientExceptionTest.java
=> fix ClientException without http status code during auth failure

odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/authentication/ClientCredentialsAccessTokenProvider.java, odata-client-microsoft-client-builder/src/test/java/com/github/davidmoten/microsoft/authentication/ClientCredentialAccessTokenProviderTest.java, odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/MsGraphMain.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ClientException.java
=> extract response code from IOException for failed authentication 

README.md
Hi @davidmoten 
As discussed via email, here's an update to documentation to address the issues I had while discovering how to make it work (with your help in issue #160 )
Adds documentation on how to generate the classes for a custom OData (non-microsoft) API and how to access it
authorizing the thing with JWT Tokens.
Also completes the example for the pom.xml file
=> Add docs for generating classes custom service

odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java
Support was added to the HTTP client classes recently in commit 06c0a1282e8347a8f73b00a3576c30fbb7f74ff1 to return response bodies from PUT, PATCH and DELETE methods but TestingService was not updated to reflect that new reality. This PR fixes that.
=> Support returning response body from put, patch, delete in TestingService

odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-msgraph/src/test/resources/response-drive.json, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CustomRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java, odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test1ServiceTest.java
and demonstrate unit test of custom request (client._custom).
As discussed in #173.
=> Fix TestingService post empty content, fix bug in custom request post

odata-client-runtime/pom.xml
Fixes issue  #209 by using the eclipse jaxb artifacts instead of sun artifacts (same versions)
=> use org.glassfish.jaxb artifacts instead of com.sun.xml.bind

odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Generator.java
To help out with #259 this PR ensures code generation support for an entity without keys.
=> Support entities without keys

odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java
When stronger delivery guarantees are desired (idempotency for one) then a two-phase send is required. For example
1. create a draft message
2. persist the draft message id somewhere (e.g. a database)
3. send the message with the stored id
To this end, the Email builder now includes two-phase send support.
=> add two-phase send to Email builder

odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ParameterMap.java, odata-client-runtime/src/test/java/com/github/davidmoten/odata/client/internal/ParameterMapTest.java
=> fix NPE in ParameterMap.toMap due JDK bug

odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/ActionFunctionRequestBase.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionRequestOptions.java
=> fix case of orderby and deltatoken in queries #435

odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/EntityRequest.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java, odata-client-test-unit/pom.xml, odata-client-test-unit/src/main/odata/metadata10.xml, odata-client-test-unit/src/main/odata/metadata7.xml, odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test10ServiceTest.java, odata-client-test-unit/src/test/java/com/github/davidmoten/odata/test/Test7ServiceTest.java, odata-client-test-unit/src/test/resources/response-complex-type-poly.json, odata-client-test-unit/src/test/resources/response-thing-poly.json
=> Support single entity request polymorphic deserialization

odata-client-microsoft-analytics/src/main/java/com/github/davidmoten/microsoft/analytics/Analytics.java, odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/authentication/ClientCredentialsAccessTokenProvider.java, odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/client/builder/MicrosoftClientBuilder.java, odata-client-microsoft-client-builder/src/test/java/com/github/davidmoten/microsoft/authentication/DynamicsCrmExample.java, odata-client-microsoft-client-builder/src/test/java/com/github/davidmoten/microsoft/authentication/DynamicsCrmExampleTest.java, odata-client-msgraph-beta/src/main/java/com/github/davidmoten/msgraph/beta/MsGraph.java, odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/MsGraph.java
… and improve intermediate builder naming
This PR means that an oauth2 client credentials token provider can be configured like [this](https://github.com/davidmoten/odata-client/pull/463/files#diff-802ee9a1d3b2ca78474343b8249c89360570891720ff58cf7cbd4e0b38d43848R14-R24)
=> refactor and enhance ClientCredentialsAccessTokenProvider and MicroftClientBuilder to support on-prem

odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/RequestHelper.java
Raised in #473, quite a simple fix
=> post with return should accept 2XX status code #473 (not just 201)

odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Names.java, odata-client-generator/src/main/java/com/github/davidmoten/odata/client/generator/Options.java, odata-client-generator/src/main/odata/msgraph-metadata.xml, odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/client/builder/MicrosoftClientBuilder.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/CollectionPage.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/HttpMethod.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/TestingService.java, odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/UnmappedFieldsImpl.java, odata-client-test-datascope/pom.xml, odata-client-test-northwind/pom.xml, odata-client-test-olingo-trip-pin/pom.xml, odata-client-test-sample-server/pom.xml, odata-client-test-service/pom.xml, odata-client-test-trip-pin/pom.xml, odata-client-test-unit/pom.xml, pom.xml
This pull request includes multiple changes across the codebase, focusing on improving code readability, ensuring immutability, simplifying exception handling, and updating Maven configurations. Below is a summary of the most important changes grouped by theme.
* Added new reserved keywords (`"clone"`, `"wait"`, `"notify"`, `"notifyAll"`) to the list in `Names.java` to ensure proper handling of Java reserved words during code generation.
* Simplified exception handling in `Names.java` and `Options.java` by replacing multi-line lambda expressions with single-line expressions for `orElseThrow`. [[1]](diffhunk://#diff-cd625231881db7f9607c006220bfc92a0cd1638ebdd9b12586c58318fabdccd4L501-R502) [[2]](diffhunk://#diff-e9226ddf2c7faed6a6cb9db8167de2ed4ce687369f5bdcbbc10c349510a3b2e1L25-R26)
* …
=> Use Central Publisher Portal, upgrade msgraph v1.0 metadata 2025-06-10, minor fixes and cleanup
